project/carts/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='carts_detail'),
    path('add/<int:product_id>/', views.cart_add, name='carts_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='carts_remove'),
    path('buy/', views.buy, name='carts_buy')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.views import *
from carts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('carts.urls', namespace='carts')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/shop/urls.py
from django.urls import path
from . import views
from project import settings
from django.conf.urls.static import static

app_name='shop'

urlpatterns = [
    path('help', views.help, name='help'),
    path('item/<int:item_id>', views.detail, name='detail'),
    path('', views.index, name='index'),
]

project/carts/models.py
from django.db import models

# Create your models here.

project/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Shop(models.Model):
    name = models.CharField(verbose_name="Название товара", max_length=60)
    price = models.IntegerField(verbose_name="Цена")
    photo_path = models.ImageField(verbose_name="Фото товара", upload_to="photo/%Y/%m/%d/",
                                   default='/photo/2023/09/08/pgadmin.png')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name="Категория", null=True)
    description = models.TextField(verbose_name="Описание товара", default='')
    arrival_date = models.DateField(verbose_name='Дата прибытия товара', auto_now=True)
    update_time = models.DateTimeField(verbose_name='Время последнего обновления карточки товара', auto_now=True)
    image_url = models.URLField(null=True)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse('shop.detail', kwargs={'item_id': self.pk, })

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ['-update_time']


class Category(models.Model):
    name = models.CharField(verbose_name="Категория", max_length=50, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

project/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductionForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget= forms.HiddenInput)

project/carts/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

project/cart/views.py
from django.shortcuts import render

# Create your views here.

project/carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Shop
from django.views.decorators.http import require_POST
# Create your views here.
from cloudipsp import Api, Checkout


def buy(request):
    cart = Cart(request)
    total = int(cart.get_total_price())
    api = Api(merchant_id=1396424,
              secret_key='test')
    checkout = Checkout(api=api)

    data = {
        "currency": "KZT",
        "amount": str(total)+'00'
    }
    url = checkout.url(data).get('checkout_url')
    return redirect(url)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Shop, id=product_id)
    form = CartAddProductForm(request.POST)
    print(form['quantity'])
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    else:
        print(form.errors)
    return redirect('carts:carts_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Shop, id=product_id)
    cart.remove(product)
    return redirect('carts:carts_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'carts/detail.html', {'cart': cart})

project/shop/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import *
from carts.forms import CartAddProductForm


# Create your views here.

def index(request):
    items = Shop.objects.all()
    return render(request, 'shop/index.html', {'items': items})


def help(request):
    return HttpResponse("Help is here")


def detail(request, item_id):
    try:
        item: object = Shop.objects.get(id=item_id)
        cart_product_form = CartAddProductForm()
    except:
        return redirect(index, permanent=True)

    return render(request, 'shop/detail.html', {'item': item, 'cart_product_form': cart_product_form})

project/carts/templates/carts/detail.html
{%extends 'shop/base.html'%}
{% load static %}

{%block content%}

<h1>Корзина покупок</h1>

<table class="cart">
    <thead>
    <tr>
        <th> Картинка </th>
        <th> Товар </th>
        <th> Обновить кол-во </th>
        <th> Удалить </th>
        <th> Кол-во </th>
        <th> Цена за шт </th>
        <th> Общая стоимость </th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product%}
        <tr>
            <td>
                <a href="{{product.get_absolute_url}}">
                    <img src="/media/{{product.photo_path}}" height="300"  width="500" style="margin: 50 px">
                </a>
            </td>
            <td>
                {{product.name}}
            </td>
            <td>
                <form action="{% url 'cart:carts_add' product.id %}" method="post">
                    {{item.update_quantity_form.quantity}}
                    {{item.update_quantity_form.update}}
                    <input type="submit" value="Обновить">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <a href="{% url 'cart:carts_remove' product.id %}">Удалить</a>
            </td>
            <td>
                {{item.quantity}}
            </td>
            <td class="num">
                {{item.price}} Тг
            </td>
            <td class="num">
                {{item.total_price}} Тг
            </td>
        </tr>
        {%endwith%}
    {%endfor%}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="sum">{{cart.get_total_price}} Тг</td>
    </tr>
    </tbody>
</table>

<p class="text-right">
    <a href="{% url 'shop:index' %}">Продолжить покупки</a>
    <a href="{% url 'carts:carts_buy' %}">Оформить заказ</a>
</p>

{%endblock%}

project/shop/templates/shop/base.html
<!Doctype html>
{%load static%}
<html lang="en" data-bs-theme="auto">
  <head>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>My Shop</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

{%block head%} {%endblock%}
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>

        <div id="subheader">
          <div class="cart">
            {% with total_items=cart|length %}
            {% if cart|length > 0%}
            В корзине:
            <a href="{%url 'carts:carts_detail'%}">
              {{total_items}} шт, {{cart.get_total_price}} Тг
            </a>
            {%else%}
            Корзина пустая
            {%endif%}
            {%endwith%}
          </div>
        </div>

      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
{%block content%}

{%endblock%}

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    </body>
</html>

project/shop/templates/shop/detail.html
{%extends 'shop/base.html'%}
{%load static%}
{%block content%}

        <div class="col">
          <div class="card shadow-sm">
            <img src="{{item.photo_path.url}}"  height="40%" width="40%">
            <div class="card-body">
              <p class="card-text">{{item.name}}</p>
              <p class="card-text">{{item.description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <form action="{%url 'carts:carts_add' item.id%}" method="post">
                    {{cart_product_form}}
                    {% csrf_token %}
                    <input type="submit" class="btn btn-sm btn-outline-secondary" value="Добавить в корзину">

                  </form>
                </div>
                <small class="text-body-secondary">Цена: {{item.price}}</small>
              </div>
            </div>
          </div>
        </div>
{%endblock%}

project/shop/templates/shop/index.html
{%extends 'shop/base.html'%}

{%block content%}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {%for item in items%}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{item.image_url}}">
            <div class="card-body">
              <p class="card-text">{{item.name}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="item/{{item.id}}"><button type="button" class="btn btn-sm btn-outline-secondary">Подробнее</button></a>
                  <a href="#"><button type="button" class="btn btn-sm btn-outline-secondary">Купить</button> </a>
                </div>
                <small class="text-body-secondary">Цена: {{item.price}}</small>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
{%endblock%}